# This workflow uses a remote action to do some repository actions like updating the readme files

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  workflow_dispatch:

jobs:
  call_update_readme: 
    uses: WorldHealthOrganization/smart-base/.github/workflows/update_readme.yml@main
